#cloud-config
packages:
  - curl
users:
  - name: chris
    ssh-authorized-keys:
      - ${trimspace(own_public)}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
  - name: cluster
    ssh-authorized-keys:
      - ${trimspace(own_public)}
      - ${trimspace(worker_public)}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - apt-get update -y
  - curl https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
  - chown cluster:cluster /etc/rancher/k3s/k3s.yaml
  - chown cluster:cluster /var/lib/rancher/k3s/server/node-token